language: cpp
sudo: required
compiler:
  - g++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"


before_install:
    - eval "${MATRIX_EVAL}"

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install bison

script: 
  - cd build/ 
  - make