language: cpp
sudo: required
compiler:
  - g++

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"


before_install:
    - eval "${MATRIX_EVAL}"
    - sudo pip install -U cpp-coveralls

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install bison
  - sudo apt-get install -y libgtest-dev cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake .
  - sudo make
  - sudo cp -a include/gtest /usr/local/include
  - sudo cp -a libgtest_main.a libgtest.a /usr/local/lib/
  - cd ../

script: 
  - cd build/ 
  - make build_cov
  - cp ./CFortranTranslator ../bin/CFortranTranslator
  - make lib_cov
  - make install
  
after_success:
  - make run_coveralls MODE=COV