/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h"
#define USE_FORARRAY
int main()
{
	const char * aaa = "hello, wolrd!";
	const char * fff = "%s\n";
	forprint(fff, aaa);
	stop();
	return 0;
}