/**********************************************************************/
/* File:                                                              */
/* Author:                                                            */
/* This codes is generated by CFortranTranslator                      */
/* CFortranTranslator is published under GPL license                  */
/* refer to https://github.com/CalvinNeo/CFortranTranslator/ for more */
/**********************************************************************/
#include "../for90std/for90std.h"
#define USE_FORARRAY
#define USE_CARRAY
int main()
{
	forprintfree("hello, world!");
	forprintfree( formap([&](int x) {return x + 1; }, 1) );
	farray<int> a({ 1 }, { 3 });
	a = make_init_list({1, 2, 3});
	forprintfree(formap([&](int x) {return x + 1; }, 1));
	forprintfree(formap([&](int x) {return x + 1; }, a));
	stop();
	return 0;
}